services:
  - type: database
    env:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  - type: web
    name: app
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${db.INTERNAL_HOSTNAME}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    envVars:
      - fromDatabase:
          name: db
