services:
  - type: web
    name: encurta-ai-app
    env: docker
    image: alanzingg/spring-boot-encurta-ai:1.0
    plan: free
    envVars:
      - file: ./env/app.env
    routes:
      - type: http
        name: encurta-ai-app-route
        port: 8080
    startCommand: "java -jar /app.jar"
    healthCheckPath: "/actuator/health"

  - type: worker
    name: postgres-db
    databaseType: postgresql
    image: postgres:latest
    plan: free
    envVars:
      - file: ./env/postgres.env
    startCommand: "postgres"
    persistentStorage:
      - name: postgres-data
        mountPath: /var/lib/postgresql/data
    healthCheckCommand: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
    healthCheckIntervalSeconds: 10
    healthCheckTimeoutSeconds: 5
    healthCheckMaxRetries: 5
    serviceDependencies:
      - name: encurta-ai-app
        condition: service_healthy
